### ISSUE TITLE
Dependabot throws a security vulnerability alert when the repo is created

### ISSUE THREAD

**Issue by mickeygousset** [githubtraining/continuous-delivery-azure#22]
**Describe the bug**
Once you queue up the lab, and it creates a repo, Dependabot throws an alert about a security vulnerability in **elliptic**.  I think users may find this a little jarring.

**To Reproduce**
1. Start the course
2. When you are navigated automatically to the first pull request, you will see a yellow box at the top of the page, indicating a security vulnerability discovered by Dependabot.

**Expected behavior**
No security vulnerability errors should be thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/20031479/88971840-38435000-d27a-11ea-843e-958a5935acbb.png)

![image](https://user-images.githubusercontent.com/20031479/88971855-3da09a80-d27a-11ea-9ba4-8fa96bce7bc1.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chromium Edge
- Version: 85.0.564.17

**Comment by hectorsector** [comment]
The [template repo](https://github.com/githubtraining/continuous-delivery-azure-template) should be alerting us, but there's a known issue https://github.com/github/dsp-security-workflows/issues/810 that's causing that not to occur. In the meantime, I'll team up with @brianamarie on pushing up a fix but it'll need a little testing before we can close this out since it'll update more than just the one dependency.
